/// <reference types="vitest/globals" />
/**
 * Integration tests: Excel glossary parser with real .xlsx fixture.
 *
 * Tests parseExcel() against a real .xlsx file generated by ExcelJS,
 * covering column mapping, NFKC normalization, whitespace handling,
 * empty cell errors, and Thai term preservation.
 *
 * Fixture: src/test/fixtures/glossary/test-glossary.xlsx
 * Generated by: src/test/fixtures/glossary/generate-xlsx.mjs
 */

import { readFileSync } from 'fs'
import path from 'path'

import { parseExcel } from '@/features/glossary/parsers/excelParser'
import { IMPORT_ERROR_CODES } from '@/features/glossary/types'
import type { ColumnMappingInput } from '@/features/glossary/validation/glossarySchemas'

const FIXTURE_PATH = path.resolve(process.cwd(), 'src/test/fixtures/glossary/test-glossary.xlsx')

function loadFixtureBuffer(): ArrayBuffer {
  const nodeBuf = readFileSync(FIXTURE_PATH)
  return nodeBuf.buffer.slice(nodeBuf.byteOffset, nodeBuf.byteOffset + nodeBuf.byteLength)
}

const headerMapping: ColumnMappingInput = {
  sourceColumn: 'source',
  targetColumn: 'target',
  hasHeader: true,
  delimiter: ',',
}

describe('Excel Glossary Parser — Real File Integration', () => {
  let buffer: ArrayBuffer

  beforeAll(() => {
    buffer = loadFixtureBuffer()
  })

  it('T1: should parse real .xlsx and return correct term count', async () => {
    const result = await parseExcel(buffer, headerMapping)

    // 13 data rows: 9 valid terms + 1 empty source + 1 empty target + 1 whitespace-only source
    // = 9 valid terms, 3 errors
    expect(result.terms).toHaveLength(9)
    expect(result.errors).toHaveLength(3)
  })

  it('T2: should extract source, target from correct columns by header name', async () => {
    const result = await parseExcel(buffer, headerMapping)

    // First term: System → ระบบ
    expect(result.terms[0]).toEqual(
      expect.objectContaining({
        sourceTerm: 'System',
        targetTerm: 'ระบบ',
      }),
    )

    // Second term: Database → ฐานข้อมูล
    expect(result.terms[1]).toEqual(
      expect.objectContaining({
        sourceTerm: 'Database',
        targetTerm: 'ฐานข้อมูล',
      }),
    )

    // Verify lineNumber starts at 2 (row 1 = header)
    expect(result.terms[0]!.lineNumber).toBe(2)
    expect(result.terms[1]!.lineNumber).toBe(3)
  })

  it('T3: should NFKC-normalize half-width katakana to full-width', async () => {
    const result = await parseExcel(buffer, headerMapping)

    // Row 10: Programming → half-width katakana (NFKC → full-width)
    const halfwidthInput = '\uFF8C\uFF9F\uFF9B\uFF78\uFF9E\uFF97\uFF90\uFF9D\uFF78\uFF9E'
    const expectedNfkc = halfwidthInput.normalize('NFKC')

    const programmingTerm = result.terms.find((t) => t.sourceTerm === 'Programming')
    expect(programmingTerm).toBeDefined()
    expect(programmingTerm!.targetTerm).toBe(expectedNfkc)
    // Verify it was actually normalized (not the same as input)
    expect(programmingTerm!.targetTerm).not.toBe(halfwidthInput)
  })

  it('T4: should skip empty/whitespace rows and report errors', async () => {
    const result = await parseExcel(buffer, headerMapping)

    // 3 error rows: empty source (row 11), empty target (row 12), whitespace-only source (row 13)
    const emptySourceErrors = result.errors.filter((e) => e.code === IMPORT_ERROR_CODES.EmptySource)
    const emptyTargetErrors = result.errors.filter((e) => e.code === IMPORT_ERROR_CODES.EmptyTarget)

    // Empty source: row 11 (empty string) + row 13 (whitespace-only trims to empty)
    expect(emptySourceErrors).toHaveLength(2)
    // Empty target: row 12
    expect(emptyTargetErrors).toHaveLength(1)
  })

  it('T4b: should trim whitespace from valid terms', async () => {
    const result = await parseExcel(buffer, headerMapping)

    // Row 8: "  User Interface  " → should be trimmed
    const uiTerm = result.terms.find((t) => t.sourceTerm === 'User Interface')
    expect(uiTerm).toBeDefined()
    expect(uiTerm!.targetTerm).toBe('ส่วนติดต่อผู้ใช้')
  })

  it('T5: should preserve Thai terms correctly without decomposition', async () => {
    const result = await parseExcel(buffer, headerMapping)

    // Verify Thai terms are intact
    const thaiTargets = result.terms
      .map((t) => t.targetTerm)
      .filter((t) => /[\u0E00-\u0E7F]/.test(t))
    expect(thaiTargets.length).toBeGreaterThanOrEqual(7)

    // Verify specific Thai terms with sara am (U+0E33) are preserved
    const participationTerm = result.terms.find((t) => t.sourceTerm === 'Participation')
    expect(participationTerm).toBeDefined()
    expect(participationTerm!.targetTerm).toBe('การมีส่วนร่วม'.normalize('NFKC'))

    // Verify compound Thai terms
    const mlTerm = result.terms.find((t) => t.sourceTerm === 'Machine Learning')
    expect(mlTerm).toBeDefined()
    expect(mlTerm!.targetTerm).toBe('การเรียนรู้ของเครื่อง')

    // Verify special characters preserved
    const cppTerm = result.terms.find((t) => t.sourceTerm === 'C++ / C#')
    expect(cppTerm).toBeDefined()
    expect(cppTerm!.targetTerm).toBe('ซีพลัสพลัส / ซีชาร์ป')
  })
})
