'use client'

import { Check, X } from 'lucide-react'

import { ConfidenceBadge } from '@/features/review/components/ConfidenceBadge'
import { LayerBadge } from '@/features/review/components/LayerBadge'
import { SeverityIndicator } from '@/features/review/components/SeverityIndicator'
import type { FindingForDisplay } from '@/features/review/types'
import { useReducedMotion } from '@/hooks/useReducedMotion'
import { PRIMARY_MODELS } from '@/types/pipeline'

export type FindingCardProps = {
  finding: FindingForDisplay
  findingIndex: number
  totalFindings: number
  sourceLang?: string | undefined
  targetLang?: string | undefined
  l2ConfidenceMin?: number | null | undefined
  l3ConfidenceMin?: number | null | undefined
  isNew?: boolean | undefined
}

const L3_CONFIRMED_MARKER = '[L3 Confirmed]'
const L3_DISAGREES_MARKER = '[L3 Disagrees]'

const CJK_LANGS = new Set(['ja', 'zh', 'ko', 'ja-JP', 'zh-CN', 'zh-TW', 'ko-KR'])
function isCjkLang(lang: string | undefined): boolean {
  if (!lang) return false
  return (
    CJK_LANGS.has(lang) || lang.startsWith('ja') || lang.startsWith('zh') || lang.startsWith('ko')
  )
}

function stripL3Markers(text: string): string {
  return text.replaceAll(L3_CONFIRMED_MARKER, '').replaceAll(L3_DISAGREES_MARKER, '').trim()
}

/** State-based background color tokens from Story 4.0 */
const STATUS_BG: Record<string, string> = {
  accepted: 'bg-[var(--color-finding-accepted)]',
  re_accepted: 'bg-[var(--color-finding-accepted)]',
  rejected: 'bg-[var(--color-finding-rejected)]',
  flagged: 'bg-[var(--color-finding-flagged)]',
  noted: 'bg-[var(--color-finding-noted)]',
  source_issue: 'bg-[var(--color-finding-source-issue)]',
}

export function FindingCard({
  finding,
  findingIndex,
  totalFindings,
  sourceLang,
  targetLang,
  l2ConfidenceMin,
  l3ConfidenceMin,
  isNew,
}: FindingCardProps) {
  const reducedMotion = useReducedMotion()

  const l3Confirmed = finding.description.includes(L3_CONFIRMED_MARKER)
  const l3Disagrees = finding.description.includes(L3_DISAGREES_MARKER)
  const cleanDescription = stripL3Markers(finding.description)

  // Fallback badge detection
  const isFallback =
    finding.aiModel !== null &&
    finding.detectedByLayer !== 'L1' &&
    finding.aiModel !== PRIMARY_MODELS[finding.detectedByLayer]

  // Confidence threshold
  const rawConfidenceMin = finding.detectedByLayer === 'L3' ? l3ConfidenceMin : l2ConfidenceMin
  const confidenceMin =
    typeof rawConfidenceMin === 'number' && Number.isFinite(rawConfidenceMin)
      ? rawConfidenceMin
      : null

  const showAnimation = isNew === true && !reducedMotion
  const bgClass = STATUS_BG[finding.status] ?? ''

  return (
    <div
      role="row"
      data-testid="finding-card"
      data-finding-id={finding.id}
      aria-expanded="true"
      className={`border rounded-lg p-3 ${bgClass} ${showAnimation ? 'animate-fade-in' : ''}`}
    >
      {/* Header row: severity + category + layer + finding number */}
      <div className="flex items-center gap-2 flex-wrap">
        <SeverityIndicator severity={finding.severity} />

        <span className="text-xs text-muted-foreground">{finding.category}</span>

        <LayerBadge layer={finding.detectedByLayer} />

        {/* L3 markers */}
        {l3Confirmed && (
          <span
            data-testid="l3-confirm-badge"
            className="inline-flex items-center rounded px-1.5 py-0.5 text-xs font-medium bg-status-pass/10 text-status-pass border border-status-pass/20"
          >
            Confirmed by L3
          </span>
        )}
        {l3Disagrees && (
          <span
            data-testid="l3-disagree-badge"
            className="inline-flex items-center rounded px-1.5 py-0.5 text-xs font-medium bg-warning/10 text-warning border border-warning/20"
          >
            L3 disagrees
          </span>
        )}

        {/* Fallback badge */}
        {isFallback && (
          <span
            data-testid="fallback-badge"
            className="inline-flex items-center rounded px-1.5 py-0.5 text-xs font-medium bg-warning/10 text-warning border border-warning/20"
            title={`Generated by ${finding.aiModel}`}
          >
            Fallback
          </span>
        )}

        <span className="ml-auto text-xs text-muted-foreground">
          #{findingIndex + 1}/{totalFindings}
        </span>
      </div>

      {/* Content row: description + source/target */}
      <div className="mt-2 pt-2 border-t text-sm space-y-1">
        <p className="text-foreground">{cleanDescription}</p>

        {finding.sourceTextExcerpt !== null && (
          <p className="text-muted-foreground">
            <span className="font-medium">Source:</span>{' '}
            <span
              lang={sourceLang}
              className={isCjkLang(sourceLang) ? 'text-cjk-scale' : undefined}
            >
              {finding.sourceTextExcerpt}
            </span>
          </p>
        )}
        {finding.targetTextExcerpt !== null && (
          <p className="text-muted-foreground">
            <span className="font-medium">Target:</span>{' '}
            <span
              lang={targetLang}
              className={isCjkLang(targetLang) ? 'text-cjk-scale' : undefined}
            >
              {finding.targetTextExcerpt}
            </span>
          </p>
        )}
      </div>

      {/* Footer row: suggestion + confidence + quick actions */}
      <div className="mt-2 flex items-center gap-2 flex-wrap">
        {finding.suggestedFix !== null && (
          <p className="text-xs italic text-muted-foreground flex-1">
            Suggested: {finding.suggestedFix}
          </p>
        )}

        <ConfidenceBadge confidence={finding.aiConfidence} confidenceMin={confidenceMin} />

        {/* Quick action icons — disabled until Story 4.2 */}
        <div className="flex items-center gap-1 shrink-0">
          <button
            type="button"
            disabled
            className="opacity-50 cursor-not-allowed p-0.5 rounded"
            aria-label="Accept finding"
          >
            <Check className="h-3.5 w-3.5" aria-hidden="true" />
          </button>
          <button
            type="button"
            disabled
            className="opacity-50 cursor-not-allowed p-0.5 rounded"
            aria-label="Reject finding"
          >
            <X className="h-3.5 w-3.5" aria-hidden="true" />
          </button>
        </div>
      </div>
    </div>
  )
}
